### PR TITLE
MOSAIC/BAG2 integration

### PR DESCRIPTION
**Pull request by martinjankoehler**
## Motivation for this PR

This PR integrates the opensource version of the [MOSAIC/BAG2 flow](https://gitlab.com/mosaic_group/mosaic_BAG/opensource_db_template/-/blob/v1.2.1-iic-osic/README.md) (vulgo `opensource_db_template`) into `IIC-OSIC-TOOLS`.

The original (and still available) flow flavor (`virtuoso_template`) did require Cadence Virtuoso and related proprietary PDKs.
In contrast, `opensource_db_template` is now working fully open-source end-to-end, using `xschem`/`klayout` as DB, and is set up for `sky130A`, no longer depending on any proprietary software.

## Pending Dependencies

- klayout version `v0.28.13` is required, we'll wait for the `OpenLane` update (see https://github.com/iic-jku/IIC-OSIC-TOOLS/pull/20)

## Status (of OSS MOSAIC/BAG2)

**Working:**
- Layout and schematic generation 
- LVS
- DRC
- Common generator Tool `gen`
- Basic simulation and measurement support (*alpha*)

**TODO:**
- PEX/RCX is not yet implemented
- Simulation support is incomplete

### Example 1: "Hello World" 

After starting the container, the environment is already prepared
- Command line tool `gen` is already available (used to control/trigger BAG2 flow steps)
- `BAG2` is set up for use with PDK `sky130A`

The packages (generators, testbenches) are explicitly installed by the user, using `gen`.

```
gen --help   # see the available subcommands (similar to Git)

gen add --all-of mosaic        # install generator packages
gen add --all-of mosaic_tb   # install testbench packages

gen make amp_cs_gen    # run layout/schematic generation and LVS
gen drc amp_cs_gen       # run DRC

cd /foss/design/bag2
klayout amp_cs_generated_sky130_fd_pr.gds     # view the generated layout
xschem --rcfile xschem/xschemrc amp_cs_generated_sky130_fd_pr/amp_cs/amp_cs.s*     # view generated concrete schematic

gen sim amp_cs_gen                  # list available measurements
gen sim amp_cs_gen -m ac_tran   # run measurement and postprocessing using matplotlib
```

### Example 2: Two-stage opamp

```
gen add --all-of mosaic_opamp
gen make --gui always opamp_two_stage_fullchip_gen    # generate and open layout
```

## Attempt to be non-invasive

- As mentioned above, the environmental variables are set up
- But by default, `/foss/designs/bag2` will not be created
- Only if `gen` is invoked, `/foss/designs/bag2` and it's helper files will be created on-demand

### CODE REVIEW

**Comment by hpretl** [comment]
@martinjankoehler The latest release `2023.12` should have a KLayout with a sufficient version number. Can you please rebase and test, then we can integrate into the official next release.

**Comment by martinjankoehler** [comment]
> @martinjankoehler The latest release `2023.12` should have a KLayout with a sufficient version number. Can you please rebase and test, then we can integrate into the official next release.

Thanks for the update.

OK, I've rebased on the current `next_release` (and just - in addition to #25 - also merged PR #26 into my integration feature branch).
Then I've noticed this error:
https://github.com/iic-jku/IIC-OSIC-TOOLS/issues/29

**Comment by hpretl** [comment]
We have now merged the refactoring of the base image generation. Please rebase and update `_build/images/base/scripts/install.sh⁣` to fit into the new structure. Then, we merge, as we are getting ready for the next release, likely next week.

**Comment by martinjankoehler** [comment]
- [x] rebase to `upstream/next_release`
- [ ] building and testing image

**Comment by martinjankoehler** [comment]
I can confirm this tests well now. 
Thanks for merging!

**Comment by hpretl** [comment]
There is an issue on the integration, @martinjankoehler please take a look: https://github.com/iic-jku/IIC-OSIC-TOOLS/issues/37

**Comment by MrHighVoltage** [comment]
We reverted the changes for now. We identified issues with NGSpice (Xspice/mixed signal and some commandos can't be found, like exit) and Klayout (Klayout did not start at all).

**Pull request merged**
